CREATE TABLE Usuario (
  idUsuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre    VARCHAR2(100) NOT NULL,
  correo    VARCHAR2(100) NOT NULL,
  celular    NUMBER,         
  cedula    NUMBER,        
  CONSTRAINT uq_usuario_correo UNIQUE (correo),
  CONSTRAINT uq_usuario_cedula UNIQUE (cedula)
);


CREATE TABLE Cliente (
  idUsuario NUMBER PRIMARY KEY,
  CONSTRAINT fk_cliente_usuario FOREIGN KEY (idUsuario) REFERENCES Usuario(idUsuario)
);


CREATE TABLE Conductor (
  idUsuario  NUMBER PRIMARY KEY,
  CONSTRAINT fk_conductor_usuario FOREIGN KEY (idUsuario)
    REFERENCES Usuario(idUsuario)
);


CREATE TABLE Ciudad (
    idCiudad   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     VARCHAR2(100) NOT NULL
);


CREATE TABLE Vehiculo (
  idVehiculo   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo         VARCHAR2(20) NOT NULL CHECK (tipo IN ('CARRO', 'CAMIONETA', 'MOTO')),
  marca        VARCHAR2(50),
  modelo       VARCHAR2(50),
  color        VARCHAR2(50),
  placa        VARCHAR2(20) NOT NULL UNIQUE,
  ciudadPlaca  VARCHAR2(50),
  capacidad    NUMBER CHECK (capacidad >= 0),
  nivel        VARCHAR2(20) CHECK (nivel IN ('ESTANDAR','CONFORT','LARGE')),
  idConductor  NUMBER NOT NULL,
  CONSTRAINT fk_vehiculo_conductor FOREIGN KEY (idConductor)
    REFERENCES Conductor(idUsuario)
);


CREATE TABLE Tarifa (
    idTarifa      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                  CONSTRAINT PK_Tarifa PRIMARY KEY,
    tipoServicio  VARCHAR2(20) NOT NULL
                  CONSTRAINT CK_TipoServicio CHECK (tipoServicio IN ('PASAJEROS', 'DOMICILIO', 'MERCANCIAS')),
    nivel         VARCHAR2(20) NOT NULL
                  CONSTRAINT CK_Nivel CHECK (nivel IN ('ESTANDAR', 'CONFORT', 'LARGE', 'NA')),
    valorKm       NUMBER NOT NULL
                  CONSTRAINT CK_ValorKm CHECK (valorKm >= 0),
    CONSTRAINT UQ_tipoServicio_nivel UNIQUE (tipoServicio, nivel)
);


CREATE TABLE Servicio (
  idServicio              NUMBER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_servicio           VARCHAR2(20) NOT NULL CHECK (tipo_servicio IN ('PASAJEROS','DOMICILIO','MERCANCIAS')),
  idCliente               NUMBER NOT NULL,
  idConductor             NUMBER NOT NULL,
  idVehiculo              NUMBER NOT NULL,
  idTarifa                NUMBER NOT NULL,
  duracion_minutos        NUMBER NOT NULL CHECK (duracion_minutos >= 0),
  hora_inicio             DATE NOT NULL,
  hora_fin                DATE NOT NULL,
  nivel_aplicado          VARCHAR2(20) CHECK (nivel_aplicado IN ('ESTANDAR','CONFORT','LARGE','NA')),
  tarifa_km_aplicada      NUMBER NOT NULL CHECK (tarifa_km_aplicada >= 0),
  porcentaje_comision     NUMBER NOT NULL CHECK (porcentaje_comision BETWEEN 0 AND 1),

  costo_total   NUMBER GENERATED ALWAYS AS (duracion_minutos * tarifa_km_aplicada) VIRTUAL,
  comision_valor NUMBER GENERATED ALWAYS AS ((duracion_minutos * tarifa_km_aplicada) * porcentaje_comision) VIRTUAL,

  CONSTRAINT fk_servicio_cliente FOREIGN KEY (idCliente)
    REFERENCES Cliente(idUsuario),
  CONSTRAINT fk_servicio_conductor FOREIGN KEY (idConductor)
    REFERENCES Conductor(idUsuario),
  CONSTRAINT fk_servicio_vehiculo FOREIGN KEY (idVehiculo)
    REFERENCES Vehiculo(idVehiculo),
  CONSTRAINT fk_servicio_tarifa FOREIGN KEY (idTarifa)
    REFERENCES Tarifa(idTarifa)
);


CREATE TABLE Tarjeta_credito (
  idtarjeta        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                   CONSTRAINT PK_TARJETA_CREDITO PRIMARY KEY,
  numero           NUMBER NOT NULL,
  nombre_tarjeta   VARCHAR2(100),
  fecha_vencimiento DATE NOT NULL,
  codigo           VARCHAR2(4) NOT NULL,
  CONSTRAINT UQ_TARJETA_CREDITO_NUMERO UNIQUE (numero),
  CONSTRAINT CK_codigo_tarjeta CHECK (REGEXP_LIKE(codigo, '^[0-9]{4}$'))
);


CREATE TABLE Punto (
    idPunto     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre      VARCHAR2(100),
    direccion   VARCHAR2(200) NOT NULL,
    latitud     NUMBER NOT NULL,
    longitud    NUMBER NOT NULL,
    idCiudad    NUMBER NOT NULL,
    CONSTRAINT PK_Punto PRIMARY KEY (idPunto),
    CONSTRAINT UQ_Punto_Nombre UNIQUE (nombre),
    CONSTRAINT UQ_Punto_Direccion UNIQUE (direccion),
    CONSTRAINT UQ_Punto_ll UNIQUE (latitud, longitud),
    CONSTRAINT CK_Punto_latitud CHECK (latitud BETWEEN -90 AND 90),
    CONSTRAINT CK_Punto_longitud CHECK (longitud BETWEEN -180 AND 180),
    CONSTRAINT FK_Punto_Ciudad FOREIGN KEY (idCiudad) REFERENCES Ciudad(idCiudad)
);


CREATE TABLE Restaurante (
    idRestaurante NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre        VARCHAR2(100) NOT NULL,
    idPunto       NUMBER NOT NULL,
    CONSTRAINT PK_Restaurante PRIMARY KEY (idRestaurante),
    CONSTRAINT UQ_Restaurante_Nombre UNIQUE (nombre),
    CONSTRAINT FK_Restaurante_Punto FOREIGN KEY (idPunto) REFERENCES Punto(idPunto)
);


CREATE TABLE Mapa (
    idMapa         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    idCiudad       NUMBER NOT NULL,
    idPuntoPartida NUMBER NOT NULL,
    idPuntoLlegada NUMBER NOT NULL,
    direccionAprox VARCHAR2(200) NOT NULL,
    CONSTRAINT PK_Mapa PRIMARY KEY (idMapa),
    CONSTRAINT FK_Mapa_Ciudad FOREIGN KEY (idCiudad) REFERENCES Ciudad(idCiudad),
    CONSTRAINT FK_Mapa_Punto_Partida FOREIGN KEY (idPuntoPartida) REFERENCES Punto(idPunto),
    CONSTRAINT FK_Mapa_Punto_Llegada FOREIGN KEY (idPuntoLlegada) REFERENCES Punto(idPunto)
);


CREATE TABLE Actividad (
    idActividad    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    diaSemana      NUMBER NOT NULL,
    franjasHorarias VARCHAR2(200),
    tipoServicio   VARCHAR2(20) NOT NULL,
    horaInicio     TIMESTAMP NOT NULL,
    horaFin        TIMESTAMP NOT NULL,
    idVehiculo     NUMBER NOT NULL,
    idConductor    NUMBER NOT NULL,
    CONSTRAINT PK_Actividad PRIMARY KEY (idActividad),
    CONSTRAINT CK_Actividad_DiaSemana CHECK (diaSemana BETWEEN 0 AND 6),
    CONSTRAINT CK_Actividad_TipoServicio CHECK (tipoServicio IN ('PASAJEROS','DOMICILIO','MERCANCIAS')),
    CONSTRAINT CK_Actividad_HoraFin CHECK (horaFin > horaInicio),
    CONSTRAINT FK_Actividad_Vehiculo FOREIGN KEY (idVehiculo) REFERENCES Vehiculo(idVehiculo),
    CONSTRAINT FK_Actividad_Conductor FOREIGN KEY (idConductor) REFERENCES Conductor(idUsuario)
);


CREATE TABLE Historial (
    idHistorial NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                CONSTRAINT PK_Historial PRIMARY KEY,
    idServicio NUMBER NOT NULL,
    idCliente NUMBER NOT NULL,
    idConductor NUMBER NOT NULL,
    idPuntoPartida NUMBER NOT NULL,
    idPuntoLlegada NUMBER NOT NULL,

    CONSTRAINT FK_HISTORIAL_SERVICIO FOREIGN KEY (idServicio) REFERENCES SERVICIO(idServicio),
    CONSTRAINT FK_HISTORIAL_CLIENTE FOREIGN KEY (idCliente) REFERENCES CLIENTE(idUsuario),
    CONSTRAINT FK_HISTORIAL_CONDUCTOR FOREIGN KEY (idConductor) REFERENCES CONDUCTOR(idUsuario),
    CONSTRAINT FK_HISTORIAL_PUNTO_PARTIDA FOREIGN KEY (idPuntoPartida) REFERENCES PUNTO(idPunto),
    CONSTRAINT FK_HISTORIAL_PUNTO_LLEGADA FOREIGN KEY (idPuntoLlegada) REFERENCES PUNTO(idPunto),

    CONSTRAINT UQ_HISTORIAL UNIQUE (idServicio, idCliente, idConductor)
);


CREATE TABLE Producto (
    idProducto NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
               CONSTRAINT PK_Producto PRIMARY KEY,
    idRestaurante NUMBER NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    precio NUMBER(10,2) NOT NULL,

    CONSTRAINT FK_PRODUCTO_RESTAURANTE FOREIGN KEY (idRestaurante) REFERENCES RESTAURANTE(idRestaurante),
    CONSTRAINT CK_PRODUCTO_PRECIO CHECK (precio > 0),
    CONSTRAINT UQ_PRODUCTO UNIQUE (idRestaurante, nombre)
);


CREATE TABLE Revision (
    idRevision NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
               CONSTRAINT PK_Revision PRIMARY KEY,
    idServicio NUMBER NOT NULL,
    idRevisorUsuario NUMBER NOT NULL,
    idReceptorUsuario NUMBER NOT NULL,
    calificacion NUMBER NOT NULL,
    comentario VARCHAR2(255),

    CONSTRAINT FK_REVISION_SERVICIO FOREIGN KEY (idServicio) REFERENCES SERVICIO(idServicio),
    CONSTRAINT FK_REVISION_REVISOR FOREIGN KEY (idRevisorUsuario) REFERENCES USUARIO(idUsuario),
    CONSTRAINT FK_REVISION_RECEPTOR FOREIGN KEY (idReceptorUsuario) REFERENCES USUARIO(idUsuario),
    CONSTRAINT CK_REVISION_CALIFICACION CHECK (calificacion BETWEEN 1 AND 5)
);


CREATE TABLE Servicio_Punto (
    idServicio     NUMBER       NOT NULL,
    rol            VARCHAR2(20) NOT NULL,
    orden          NUMBER       NOT NULL,
    idPunto        NUMBER       NOT NULL,
    CONSTRAINT PK_Servicio_Punto 
        PRIMARY KEY (idServicio, rol, orden),
    CONSTRAINT UQ_Servicio_Punto UNIQUE (rol, idServicio, orden),
    CONSTRAINT CK_Servicio_Punto_Rol 
        CHECK (rol IN ('PARTIDA', 'LLEGADA', 'RESTAURANTE')),
    CONSTRAINT CK_Servicio_Punto_Orden 
        CHECK (orden >= 1),
    CONSTRAINT FK_Servicio_Punto_IdPunto 
    FOREIGN KEY (idPunto) REFERENCES Punto(idPunto),
CONSTRAINT FK_Servicio_Punto_Servicio
    FOREIGN KEY (idServicio) REFERENCES Servicio(idServicio)
);


CREATE TABLE Servicio_Pasajeros (
    idServicio        NUMBER NOT NULL,
    Cantidad_pasajeros NUMBER NOT NULL,
    CONSTRAINT PK_Servicio_Pasajeros 
        PRIMARY KEY (idServicio),
    CONSTRAINT FK_Servicio_Pasajeros_Servicio
        FOREIGN KEY (idServicio) REFERENCES Servicio(idServicio),
    CONSTRAINT CK_Servicio_Pasajeros 
        CHECK (Cantidad_pasajeros >= 1)
);


CREATE TABLE Servicio_Domicilio (
    idServicio          NUMBER NOT NULL,
    idRestaurante       NUMBER NOT NULL,
    Valor_Orden         NUMBER NOT NULL,
    Cantidad_Productos  NUMBER NOT NULL,
    CONSTRAINT PK_Servicio_Domicilio 
        PRIMARY KEY (idServicio),
    CONSTRAINT FK_Servicio_Domicilio_Servicio
        FOREIGN KEY (idServicio) REFERENCES Servicio(idServicio),
    CONSTRAINT FK_Servicio_Domicilio_IdRest 
        FOREIGN KEY (idRestaurante) REFERENCES Restaurante(idRestaurante),
    CONSTRAINT CK_Servicio_Domicilio_Valor 
        CHECK (Valor_Orden >= 0),
    CONSTRAINT CK_Servicio_Domicilio_Productos 
        CHECK (Cantidad_Productos >= 0)
);


CREATE TABLE Servicio_Mercancias (
    idServicio       NUMBER NOT NULL,
    Cantidad_Objetos NUMBER NOT NULL,
    CONSTRAINT PK_Servicio_Mercancias 
        PRIMARY KEY (idServicio),
    CONSTRAINT FK_Servicio_Mercancias_Servicio
        FOREIGN KEY (idServicio) REFERENCES Servicio(idServicio),
	
	
    CONSTRAINT CK_Servicio_Mercancias 
        CHECK (Cantidad_Objetos >= 0)
);


CREATE TABLE Pago (
  idPago        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                CONSTRAINT PK_Pago PRIMARY KEY,
  idServicio    NUMBER NOT NULL,
  idTarjeta     NUMBER NOT NULL,
  monto         NUMBER(10,2) NOT NULL CHECK (monto >= 0),
  fecha_pago    DATE DEFAULT SYSDATE NOT NULL,

  CONSTRAINT FK_Pago_Servicio FOREIGN KEY (idServicio)
      REFERENCES Servicio(idServicio),
  CONSTRAINT FK_Pago_Tarjeta FOREIGN KEY (idTarjeta)
      REFERENCES Tarjeta_credito(idTarjeta),
  CONSTRAINT UQ_Pago_Servicio UNIQUE (idServicio) 
);


-- Tabla de Disponibilidad (requerida por RF5)
-- Nota: Se modela con campos de fecha/hora como texto (YYYY-MM-DD y HH:MM) para
-- que las comparaciones utilizadas por la aplicación funcionen de forma determinística.
CREATE TABLE Disponibilidad (
    id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                 CONSTRAINT PK_Disponibilidad PRIMARY KEY,
    idConductor  NUMBER NOT NULL,
    idVehiculo   NUMBER NOT NULL,
    tipoServicio VARCHAR2(20) NOT NULL
                 CONSTRAINT CK_Disponibilidad_TipoServicio
                 CHECK (tipoServicio IN ('PASAJEROS','DOMICILIO','MERCANCIAS')),
    diaInicio    VARCHAR2(10) NOT NULL, -- formato esperado: YYYY-MM-DD
    diaFin      VARCHAR2(10) NOT NULL,  -- formato esperado: YYYY-MM-DD
    horaInicio  VARCHAR2(5)  NOT NULL,  -- formato esperado: HH:MM (con cero inicial)
    horaFin     VARCHAR2(5)  NOT NULL,  -- formato esperado: HH:MM (con cero inicial)

    CONSTRAINT FK_Disponibilidad_Conductor
        FOREIGN KEY (idConductor) REFERENCES Conductor(idUsuario),
    CONSTRAINT FK_Disponibilidad_Vehiculo
        FOREIGN KEY (idVehiculo)  REFERENCES Vehiculo(idVehiculo)
);

-- Índices de apoyo para búsquedas por conductor y rangos
CREATE INDEX IX_Disponibilidad_Conductor ON Disponibilidad(idConductor);
CREATE INDEX IX_Disponibilidad_Vehiculo  ON Disponibilidad(idVehiculo);


